### ISSUE TITLE
Binary...

### ISSUE THREAD

**Issue by cymen** [ralphtheninja/await-spawn#2]
I tried using this for a binary stream and unfortunately this line:

https://github.com/ralphtheninja/await-spawn/blob/master/index.js#L19

Is no good -- for binary, we wouldn't want a `toString` on it. I'm not sure if there is a way to tell if a buffer has string or binary contents. So no idea on a solution. But I wanted to point out that line is limiting usage to strings.

I ended up using `bl` directly and dropping `await-spawn` so not blocked and don't need a solution or anything like that.

**Comment by ralphtheninja** [comment]
Good catch. Never thought about it because just made the module for myself.

**Comment by ralphtheninja** [comment]
We could skip the `.toString()` completely and just callback with `bl`

**Comment by cymen** [comment]
That was what I was thinking but I realized your API would change. An alternative might be to make `await-spawn-binary` or some similar name and have `await-spawn` consume it but do a `toString` on the returned value from `await-spawn-binary`?

I'm guessing the issue with just returning `bl` for string contents is then it's a buffer and not a string which I could see being annoying.

**Comment by ralphtheninja** [comment]
Nah, changing the API is not a problem. Just release a new major :)

**Comment by ralphtheninja** [comment]
2.0.0

**Comment by ralphtheninja** [comment]
Re-open if you need to discuss further. :clinking_glasses:
